server:
  port: 8081
  servlet:
    context-path: /app

spring:
  mvc:
    static-path-pattern: /upload/**
  resources:

  redis:
    host: localhost
    port: 6379
  datasource:
#    username: faqrobot
#    password: N5AFzUgI3uDml4zk
#    url: jdbc:mysql://192.168.1.69:3306/v5_test_cs?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    multiple:
      low:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/fortest?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
      high:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/fortest2?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:default/
